services:
  - type: web
    name: newchemia
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # CREDENCIALES/SECRETS (usa Dashboard → Environment → Add env var en vez de poner valores aquí):
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SHEETS_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: AGENT_TOKEN
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://newchemia.onrender.com
